import { fileURLToPath, URL } from 'node:url'

import { defineConfig, type UserConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'
import tailwindcss from '@tailwindcss/vite'
import vueDevTools from 'vite-plugin-vue-devtools'
import { resolve } from 'node:path'
import { readdirSync } from 'node:fs'
import { existsSync, readFileSync } from 'node:fs'
import { CssBuildPlugin, HmrIdsPlugin, VuetalePlugin } from 'vuetale/vite'

const __dirname = fileURLToPath(new URL('.', import.meta.url))

// Fallback for vuetale-companion which has import issues
const NATIVE_UI_TAGS = new Set<string>()

// Module aliases generated by `extract-dts` – maps e.g. '@core' → resolved output path.
// Falls back to an empty object when the aliases file has not been generated yet.
function loadVuetaleAliases(): Record<string, string> {
  const aliasesFile = resolve(__dirname, '.vuetale/aliases.json')
  if (!existsSync(aliasesFile)) return {}
  try {
    return JSON.parse(readFileSync(aliasesFile, 'utf-8'))
  } catch {
    return {}
  }
}

const vuetaleAliases = loadVuetaleAliases()

function getComponentEntries() {
  const componentsDir = resolve(__dirname, 'lib/components')
  return readdirSync(componentsDir)
    .filter(file => file.endsWith('.vue'))
    .reduce((entries, file) => {
      const name = file.replace('.vue', '')
      entries[name] = resolve(componentsDir, file)
      return entries
    }, {} as Record<string, string>)
}

function getScriptEntries(mode: string) {
  const scriptsDir = resolve(__dirname, 'lib')
  return readdirSync(scriptsDir)
    .filter(file => file.endsWith('.ts'))
    // debug.ts is only useful in dev mode – skip it in production builds
    .filter(file => mode === 'development' || file !== 'debug.ts')
    .reduce((entries, file) => {
      const name = file.replace('.ts', '')
      entries[name] = resolve(scriptsDir, file)
      return entries
    }, {} as Record<string, string>)
}


function getPageEntries() {
  const pagesDir = resolve(__dirname, 'lib/pages')
  return readdirSync(pagesDir)
    .filter(file => file.endsWith('.vue'))
    .reduce((entries, file) => {
      const name = file.replace('.vue', '')
      entries[name] = resolve(pagesDir, file)
      return entries
    }, {} as Record<string, string>)
}

// https://vite.dev/config/
export default defineConfig(({ mode }): UserConfig => ({
  plugins: [
    tailwindcss(),
    vue({
      template: {
        compilerOptions: {
          // Treat custom renderer tags as native elements instead of Vue components.
          isCustomElement: (tag) => NATIVE_UI_TAGS.has(tag),
        },
      },
    }),
    vueJsx(),
    vueDevTools(),
    // @ts-expect-error - vite version may mismatch slightly
    VuetalePlugin(),
    // @ts-expect-error - vite version may mismatch slightly
    CssBuildPlugin(),
    // @ts-expect-error - vite version may mismatch slightly
    HmrIdsPlugin(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./lib', import.meta.url)),
      ...vuetaleAliases,
    },
  },
  build: {
    cssCodeSplit: true,
    sourcemap: 'inline',
    lib: {
      entry: {
        // you can still have a main barrel if you want
        // index: resolve(__dirname, 'src/index.ts'),
        ...getPageEntries(),   // Button, Card, Modal, ...
        ...getComponentEntries(),
        ...getScriptEntries(mode),
      },
      formats: ['es'],
      fileName: (_, entryName) => `${entryName}.js`
    },


    rollupOptions: {
      external: (id) => {
        if (id === 'vue') return true
        if (id.startsWith('vt:')) return true
      },
      output: {
        preserveModules: true,
        entryFileNames: '[name].js',

      },
    },

    outDir: 'dist',
    //outDir: '../main/resources/vuetale/' + vuetaleConfig.name,
    emptyOutDir: true
  }
}))
